language: python
cache:
  directories:
    - $HOME/google-cloud-sdk
install:
  - if [ ! -d $HOME/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
deploy:
  provider: gae
  keyfile: JSON
  key: private_key
  project name: project
  edge: true
  on:
    branch: main
script:
  - echo "hello world!!!"
