language: python
python:
- "3.8"
deploy:
  provider: gae
  keyfile: $JSON
  key: $private_key
  project name: $project_id
  edge: true
  on:
    branch: main
script:
  - echo "hello world!!!"
  - gcloud -q app deploy app.yaml --project="your-project-id" --verbosity="warning"

