language: python
install:
  - curl https://sdk.cloud.google.com | bash -s -- --disable-prompts

deploy:
  provider: gae
  keyfile: JSON
  key: private_key
  project name: project
  edge: true
  on:
    branch: main
script:
  - echo "hello world!!!"
